version: '3'

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_MY_URL: jdbc:mysql://localhost:3306/cgisample?createDatabaseIfNotExist=true&user=root&password=root
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_URL: mongodb://localhost:27017/dockmongodb
  userservice:
    image: kalppatel/userservice-image
    network_mode: host
    depends_on:
      - mysqldb
    restart: always
    ports:
      - 9091:9091
  Restaurant:
    image: kalppatel/restaurant-image
    network_mode: host
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8083:8083
  Order:
    image: kalppatel/order-image
    network_mode: host
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8086:8086
  Favourites:
    image: kalppatel/favourites-image
    network_mode: host
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8082:8082
